/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    artists: Artist;
    filters: Filter;
    routes: Route;
    'mp3-records': Mp3Record;
    partners: Partner;
    contacts: Contact;
    articles: Article;
    notifications: Notification;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    filters: FiltersSelect<false> | FiltersSelect<true>;
    routes: RoutesSelect<false> | RoutesSelect<true>;
    'mp3-records': Mp3RecordsSelect<false> | Mp3RecordsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('sk' | 'en') | ('sk' | 'en')[];
  globals: {
    'festival-settings': FestivalSetting;
    'ticket-settings': TicketSetting;
    'practical-info': PracticalInfo;
    volunteers: Volunteer;
    'support-us': SupportUs;
    'press-kit': PressKit;
    'about-page': AboutPage;
    'branding-settings': BrandingSetting;
    'navigation-settings': NavigationSetting;
  };
  globalsSelect: {
    'festival-settings': FestivalSettingsSelect<false> | FestivalSettingsSelect<true>;
    'ticket-settings': TicketSettingsSelect<false> | TicketSettingsSelect<true>;
    'practical-info': PracticalInfoSelect<false> | PracticalInfoSelect<true>;
    volunteers: VolunteersSelect<false> | VolunteersSelect<true>;
    'support-us': SupportUsSelect<false> | SupportUsSelect<true>;
    'press-kit': PressKitSelect<false> | PressKitSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'branding-settings': BrandingSettingsSelect<false> | BrandingSettingsSelect<true>;
    'navigation-settings': NavigationSettingsSelect<false> | NavigationSettingsSelect<true>;
  };
  locale: 'sk' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: number;
  name: string;
  work?: string | null;
  image?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  place?: string | null;
  /**
   * Auto-filled from map
   */
  latitude?: number | null;
  /**
   * Auto-filled from map
   */
  longitude?: number | null;
  performance?: string | null;
  genre?: string | null;
  year: '2020' | '2021' | '2022' | '2023' | '2024' | '2025' | '2026' | '2027' | '2028' | '2029' | '2030';
  city: 'ba' | 'ke';
  /**
   * Display order (lower = first)
   */
  hierarchy?: number | null;
  paid?: boolean | null;
  filters?: (number | Filter)[] | null;
  routes?: (number | Route)[] | null;
  dates?:
    | {
        start?: string | null;
        end?: string | null;
        display?: boolean | null;
        id?: string | null;
      }[]
    | null;
  records?: (number | Mp3Record)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filters".
 */
export interface Filter {
  id: number;
  title: string;
  slug: string;
  /**
   * Hex color code (e.g. #FF5555)
   */
  color: string;
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routes".
 */
export interface Route {
  id: number;
  title: string;
  city: 'ba' | 'ke';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mp3-records".
 */
export interface Mp3Record {
  id: number;
  title: string;
  description?: string | null;
  file: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * External URL
   */
  link?: string | null;
  category:
    | 'general'
    | 'main'
    | 'partner'
    | 'official'
    | 'support'
    | 'regional'
    | 'it'
    | 'delivery'
    | 'main-media'
    | 'other-media'
    | 'appreciation';
  year: '2020' | '2021' | '2022' | '2023' | '2024' | '2025' | '2026' | '2027' | '2028' | '2029' | '2030';
  bratislava?: boolean | null;
  kosice?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  name: string;
  role?: string | null;
  email?: string | null;
  photo?: (number | null) | Media;
  /**
   * Display order (lower = first)
   */
  orderRank?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Cover image shown in article cards and carousel.
   */
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  title: string;
  description: string;
  city: 'ba' | 'ke';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'artists';
        value: number | Artist;
      } | null)
    | ({
        relationTo: 'filters';
        value: number | Filter;
      } | null)
    | ({
        relationTo: 'routes';
        value: number | Route;
      } | null)
    | ({
        relationTo: 'mp3-records';
        value: number | Mp3Record;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  name?: T;
  work?: T;
  image?: T;
  description?: T;
  place?: T;
  latitude?: T;
  longitude?: T;
  performance?: T;
  genre?: T;
  year?: T;
  city?: T;
  hierarchy?: T;
  paid?: T;
  filters?: T;
  routes?: T;
  dates?:
    | T
    | {
        start?: T;
        end?: T;
        display?: T;
        id?: T;
      };
  records?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filters_select".
 */
export interface FiltersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  color?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routes_select".
 */
export interface RoutesSelect<T extends boolean = true> {
  title?: T;
  city?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mp3-records_select".
 */
export interface Mp3RecordsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  link?: T;
  category?: T;
  year?: T;
  bratislava?: T;
  kosice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  email?: T;
  photo?: T;
  orderRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  coverImage?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  city?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "festival-settings".
 */
export interface FestivalSetting {
  id: number;
  currentYear: '2024' | '2025' | '2026' | '2027' | '2028' | '2029' | '2030';
  /**
   * e.g. "3. – 5. október 2025 Bratislava"
   */
  dateInfoBA?: string | null;
  /**
   * e.g. "10. – 12. október 2025 Košice"
   */
  dateInfoKE?: string | null;
  /**
   * When enabled, shows festival mode (artists/map/program). When off, shows off-festival landing page.
   */
  festivalActive?: boolean | null;
  /**
   * Enable debug time override on frontend (shows time picker bar)
   */
  debugMode?: boolean | null;
  /**
   * Simulated current time (only used when debug mode is on)
   */
  debugTime?: string | null;
  socialInstagram?: string | null;
  socialFacebook?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-settings".
 */
export interface TicketSetting {
  id: number;
  /**
   * Toggle ticket sales on/off
   */
  saleEnabled?: boolean | null;
  /**
   * Ticket purchase URL for Bratislava
   */
  linkBA?: string | null;
  /**
   * Ticket purchase URL for Košice
   */
  linkKE?: string | null;
  /**
   * Additional ticket info for Bratislava
   */
  textBA?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Additional ticket info for Košice
   */
  textKE?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practical-info".
 */
export interface PracticalInfo {
  id: number;
  sectionsBA?:
    | {
        title: string;
        text?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  sectionsKE?:
    | {
        title: string;
        text?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers".
 */
export interface Volunteer {
  id: number;
  contentBA?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentKE?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-us".
 */
export interface SupportUs {
  id: number;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-kit".
 */
export interface PressKit {
  id: number;
  /**
   * ZIP archive for press download
   */
  archive?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding-settings".
 */
export interface BrandingSetting {
  id: number;
  logo?: {
    /**
     * Site logo (SVG or PNG). Falls back to default if empty.
     */
    image?: (number | null) | Media;
  };
  colors?: {
    /**
     * Primary accent color (hex). Used for CTAs, highlights, active states.
     */
    accent?: string | null;
    /**
     * Bratislava section background color (homepage).
     */
    bratislavaBackground?: string | null;
    /**
     * Košice section background color (homepage).
     */
    kosiceBackground?: string | null;
    /**
     * Side menu gradient top color. Bottom is always black.
     */
    menuGradient?: string | null;
  };
  homepage?: {
    /**
     * Main homepage image for Bratislava section.
     */
    imageBA?: (number | null) | Media;
    /**
     * Image shown on hover for Bratislava section.
     */
    imageBAHover?: (number | null) | Media;
    /**
     * Main homepage image for Košice section.
     */
    imageKE?: (number | null) | Media;
    /**
     * Image shown on hover for Košice section.
     */
    imageKEHover?: (number | null) | Media;
  };
  stars?: {
    /**
     * Show decorative star dots in background.
     */
    enabled?: boolean | null;
    /**
     * Colors for star dots. Each color produces 3 dots.
     */
    colors?:
      | {
          /**
           * Hex color (e.g. #F5E455)
           */
          color: string;
          id?: string | null;
        }[]
      | null;
  };
  offSeason?: {
    /**
     * Hero banner image shown on the off-season homepage.
     */
    banner?: (number | null) | Media;
    /**
     * Main heading. Falls back to "BIELA NOC" if empty.
     */
    heading?: string | null;
    /**
     * Announcement or description text below the heading.
     */
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  footer?: {
    /**
     * Footer copyright text. Falls back to "© {year} Biela Noc".
     */
    text?: string | null;
    links?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-settings".
 */
export interface NavigationSetting {
  id: number;
  /**
   * Navigation menu links. Drag to reorder.
   */
  menuItems?:
    | {
        /**
         * Display text for the link.
         */
        label: string;
        /**
         * Path (e.g. /umelci, /mapa). If "Use year/city prefix" is on, the current year/city is prepended.
         */
        url: string;
        /**
         * Prepend /{year}/{city} to the URL automatically.
         */
        useYearCity?: boolean | null;
        icon?: ('none' | 'search') | null;
        /**
         * Show a separator line after this item.
         */
        dividerAfter?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Instagram profile URL
   */
  socialInstagram?: string | null;
  /**
   * Facebook page URL
   */
  socialFacebook?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "festival-settings_select".
 */
export interface FestivalSettingsSelect<T extends boolean = true> {
  currentYear?: T;
  dateInfoBA?: T;
  dateInfoKE?: T;
  festivalActive?: T;
  debugMode?: T;
  debugTime?: T;
  socialInstagram?: T;
  socialFacebook?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-settings_select".
 */
export interface TicketSettingsSelect<T extends boolean = true> {
  saleEnabled?: T;
  linkBA?: T;
  linkKE?: T;
  textBA?: T;
  textKE?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practical-info_select".
 */
export interface PracticalInfoSelect<T extends boolean = true> {
  sectionsBA?:
    | T
    | {
        title?: T;
        text?: T;
        icon?: T;
        id?: T;
      };
  sectionsKE?:
    | T
    | {
        title?: T;
        text?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers_select".
 */
export interface VolunteersSelect<T extends boolean = true> {
  contentBA?: T;
  contentKE?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-us_select".
 */
export interface SupportUsSelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-kit_select".
 */
export interface PressKitSelect<T extends boolean = true> {
  archive?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding-settings_select".
 */
export interface BrandingSettingsSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        image?: T;
      };
  colors?:
    | T
    | {
        accent?: T;
        bratislavaBackground?: T;
        kosiceBackground?: T;
        menuGradient?: T;
      };
  homepage?:
    | T
    | {
        imageBA?: T;
        imageBAHover?: T;
        imageKE?: T;
        imageKEHover?: T;
      };
  stars?:
    | T
    | {
        enabled?: T;
        colors?:
          | T
          | {
              color?: T;
              id?: T;
            };
      };
  offSeason?:
    | T
    | {
        banner?: T;
        heading?: T;
        text?: T;
      };
  footer?:
    | T
    | {
        text?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-settings_select".
 */
export interface NavigationSettingsSelect<T extends boolean = true> {
  menuItems?:
    | T
    | {
        label?: T;
        url?: T;
        useYearCity?: T;
        icon?: T;
        dividerAfter?: T;
        id?: T;
      };
  socialInstagram?: T;
  socialFacebook?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}